import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.overview': 'Overview',
    'nav.network': 'My Network',
    'nav.credit': 'Credit',
    'nav.communities': 'Communities',
    'nav.howItWorks': 'How It Works',
    'nav.useCases': 'Use Cases',
    'nav.faqs': 'FAQs',
    'footer.terms': 'Terms & Privacy',
    'common.connectWallet': 'Connect Wallet',
    'common.disconnect': 'Disconnect',
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.toggleLanguage': 'Toggle language',
    'common.processing': 'Processing...',
    'common.months': 'months',
    'common.members': 'members',
    'common.total': 'Total',
    'common.active': 'Active',
    'common.current': 'Current',
    'landing.title': 'MaxFlow',
    'landing.subtitle': 'Sybil-Resistant Graph Signal Infrastructure',
    'communities.title': 'Communities',
    'communities.description': 'Discover and join trust networks with custom endorsement criteria',
    'communities.create': 'Create Community',
    'communities.viewDashboard': 'View Lending Dashboard',
    'communities.myCommunities': 'My Communities',
    'communities.allCommunities': 'All Communities',
    'communities.viewDetails': 'View Details',
    'communities.dashboard': 'Dashboard',
    'communities.noCommunities': 'No communities yet',
    'communities.beFirst': 'Be the first to create a community',
    'communities.prompt': 'Prompt',
    'communities.community': 'Community',
    'communities.public': 'Public',
    'communities.private': 'Private',
    'communities.notFound': 'Community not found',
    'overview.title': 'Overview',
    'overview.description': 'Your personal trust hub: view your score, give endorsements, and manage your network',
    'credit.title': 'Credit',
    'credit.description': 'Access microloans based on your LocalHealth score',
    'credit.connectWallet': 'Connect Wallet',
    'credit.connectWalletDesc': 'Please connect your wallet to access credit',
    'credit.loadingInfo': 'Loading credit information...',
    'credit.trustProfile': 'Trust Profile',
    'credit.trustProfileDesc': 'Your trust metrics (advisory only)',
    'credit.sybilResistance': 'Sybil Resistance',
    'credit.healthIndex': 'Health Index',
    'credit.endorsedMember': 'Endorsed network member',
    'credit.metricsAdvisory': 'These metrics are advisory only. All members can apply for loans during the pilot phase.',
    'credit.noMetrics': 'No trust metrics available yet',
    'credit.noMetricsInfo': 'You can still apply for loans during the pilot phase. Get endorsements from trusted members to build your profile.',
    'credit.applyLoan': 'Apply for Loan',
    'credit.applyLoanDesc': 'Select loan amount and payment term',
    'credit.fullName': 'Full Name',
    'credit.fullNamePlaceholder': 'e.g. María González',
    'credit.loanAmount': 'Loan Amount (ARS)',
    'credit.paymentTerm': 'Payment Term',
    'credit.applyLoanButton': 'Apply for Loan',
    'credit.tabApply': 'Apply for Loan',
    'credit.tabActive': 'Active Loan',
    'credit.tabHistory': 'History',
    'credit.activeLoan': 'Active Loan',
    'credit.paymentProgress': 'Payment Progress',
    'credit.nextPayment': 'Next Payment',
    'credit.dueOn': 'due on',
    'credit.makePayment': 'Make Payment',
    'credit.makePaymentDesc': 'Pay your next installment',
    'credit.paymentAmountARS': 'Payment Amount (ARS)',
    'credit.makePaymentButton': 'Make Payment',
    'credit.loanHistory': 'Loan History',
    'credit.loanHistoryDesc': 'Your past and current loans',
    'credit.noLoans': 'No loans yet',
    'credit.statusPaid': 'PAID',
    'credit.statusActive': 'ACTIVE',
    'credit.statusDefault': 'DEFAULT',
    'credit.loanCreatedSuccess': 'Loan created successfully',
    'credit.loanDisbursed': 'Your loan has been disbursed',
    'credit.errorCreatingLoan': 'Error creating loan',
    'credit.paymentSuccess': 'Payment successful',
    'credit.paymentProcessed': 'Your payment has been processed',
    'credit.errorPayment': 'Payment error',
    'credit.errorNameRequired': 'Please enter your full name',
    'communityDetail.accepted': 'Accepted',
    'communityDetail.health': 'Health',
    'communityDetail.minCut': 'Min-Cut',
    'communityDetail.avgResistance': 'Avg Resistance',
    'communityDetail.activeLoans': 'Active Loans',
    'communityDetail.onTime': 'On-Time',
    'communityDetail.rate90d': '90d Rate',
    'communityDetail.vouches': 'Vouches',
    'communityDetail.sponsors': 'Sponsors',
    'communityDetail.tabOverview': 'Overview',
    'communityDetail.tabCredit': 'Credit',
    'communityDetail.tabSupport': 'Support',
    'communityDetail.tabTrust': 'Trust',
    'communityDetail.tabImpact': 'Impact',
    'communityDetail.tabUpdates': 'Updates',
    'communityDetail.tabPeople': 'People',
    'communityDetail.tabTransparency': 'Transparency',
    'communityDetail.trustDistribution': 'Trust Distribution',
    'communityDetail.trustDistributionDesc': 'Members by trust tier',
    'communityDetail.networkMetrics': 'Network Metrics',
    'communityDetail.networkMetricsDesc': 'Latest computation statistics',
    'communityDetail.avgFlow': 'Average Flow',
    'communityDetail.avgMinCut': 'Average Min-Cut',
    'communityDetail.activeParticipants': 'Active Participants',
    'communityDetail.graphHealth': 'Graph Health',
    'communityDetail.aboutCommunity': 'About This Community',
    'communityDetail.endorsementCriteria': 'Endorsement Criteria',
    'communityDetail.memberEndorse': 'Members endorse each other by affirming:',
    'communityDetail.cryptoVerified': 'All endorsements are cryptographically verified against the prompt hash to ensure consistency.',
    'communityDetail.connectForCredit': 'Connect Your Wallet',
    'communityDetail.connectForCreditDesc': 'Connect your wallet to check your credit eligibility and view loan offers',
    'communityDetail.creditAccess': 'Credit Access',
    'communityDetail.creditAccessDesc': 'Apply for microloans or manage your active credit',
    'communityDetail.eligibilityStatus': 'Your Eligibility Status',
    'communityDetail.eligible': 'Eligible',
    'communityDetail.notEligible': 'Not Yet Eligible',
    'communityDetail.eligibleDesc': 'You meet the trust requirements and can apply for credit in this community.',
    'communityDetail.notEligibleDesc': 'Build trust by getting endorsements from community members to unlock credit access.',
    'communityDetail.viewMyLoan': 'View My Loan',
    'communityDetail.applyForCredit': 'Apply for Credit',
    'communityDetail.viewOffers': 'View Offers',
    'communityDetail.yourActiveLoans': 'Your Active Loans',
    'communityDetail.loanNumber': 'Loan #',
    'communityDetail.principal': 'Principal',
    'communityDetail.term': 'Term',
    'communityDetail.apr': 'APR',
    'communityDetail.nextDue': 'Next Due',
    'communityDetail.howToJoin': 'How to Join This Community',
    'communityDetail.toEarnTrust': 'To earn trust in',
    'communityDetail.step1': 'Get endorsed by existing trusted members who can affirm:',
    'communityDetail.step2': 'Build redundant paths through the network (min-cut ≥',
    'communityDetail.step3': 'Ensure you have vertex-disjoint connections (≥',
    'communityDetail.step3cont': 'independent paths)',
    'communityDetail.step4': 'Maintain quality connections to at least',
    'communityDetail.step4cont': 'seed members',
    'communityDetail.step5': 'Each seed must provide ≥',
    'communityDetail.step5cont': 'of your flow',
    'communityDetail.connectForSupport': 'Connect your wallet to view and support loans in this community',
    'communityDetail.interestBuydown': 'Interest Buy-Down',
    'communityDetail.repayAssist': 'Repay-Assist',
    'communityDetail.myPortfolio': 'My Portfolio',
    'communityDetail.ibdDesc': 'Commit monthly USDC to reduce the borrower\'s interest rate',
    'communityDetail.noLoansIBD': 'No active loans available for Interest Buy-Down in this community.',
    'communityDetail.setMonthlyCommitment': 'Set Monthly Commitment',
    'communityDetail.monthlyCommitmentDesc': 'Choose how much to contribute each month to reduce the borrower\'s interest rate',
    'communityDetail.monthlyAmount': 'Monthly Amount',
    'communityDetail.commitRange': 'Commit between $100k - $2M ARS per month',
    'communityDetail.activateCommitment': 'Activate Monthly Commitment',
    'communityDetail.creating': 'Creating...',
    'communityDetail.ibdCreated': 'Interest Buy-Down Created',
    'communityDetail.ibdCreatedDesc': 'Your monthly commitment has been activated to reduce the borrower\'s interest rate.',
    'communityDetail.errorCreatingCommitment': 'Error Creating Commitment',
    'communityDetail.raActivated': 'Repay-Assist Activated',
    'communityDetail.raActivatedDesc': 'You covered the late installment. The borrower will repay you with a 6% premium.',
    'communityDetail.errorCoveringInstallment': 'Error Covering Installment',
    'communityDetail.apiIntegration': 'API Integration',
    'communityDetail.apiIntegrationDesc': 'Connect external applications to this community',
    'communityDetail.apiKey': 'API Key',
    'communityDetail.apiKeyCopied': 'API Key Copied',
    'communityDetail.apiKeyCopiedDesc': 'API key has been copied to clipboard',
    'communityDetail.apiKeyWarning': 'Keep this key secure. It allows external applications to read trust scores and submit vouches on behalf of users.',
    'communityDetail.endpoints': 'Available Endpoints',
    'createCommunity.title': 'Create a Community',
    'createCommunity.description': 'Build a community with custom endorsement criteria',
    'createCommunity.step1': '1. Choose a Template',
    'createCommunity.templateDesc': 'Select a pre-configured policy or start from scratch',
    'createCommunity.step2': '2. Community Details',
    'createCommunity.basicInfo': 'Basic Information',
    'createCommunity.communityName': 'Community Name',
    'createCommunity.communityNamePlaceholder': 'e.g. Tech Freelancers Network',
    'createCommunity.descriptionLabel': 'Description',
    'createCommunity.descriptionPlaceholder': 'Describe the purpose and goals of your community...',
    'createCommunity.endorsementPrompt': 'Endorsement Prompt',
    'createCommunity.promptPlaceholder': 'I trust this person to...',
    'createCommunity.walletRequired': 'Wallet not connected',
    'createCommunity.walletRequiredDesc': 'Please connect your wallet to create a community',
    'createCommunity.nameRequired': 'Name required',
    'createCommunity.nameRequiredDesc': 'Please enter a community name',
    'createCommunity.createButton': 'Create Community',
    'createCommunity.communityCreated': 'Community created!',
    'createCommunity.creatorFirstSeed': 'has been created. You\'re automatically the first seed.',
    'createCommunity.errorCreating': 'Error creating community',
    'createCommunity.errorCreatingDesc': 'Failed to create community',
  },
  es: {
    'nav.overview': 'Resumen',
    'nav.network': 'Mi Red',
    'nav.credit': 'Crédito',
    'nav.communities': 'Comunidades',
    'nav.howItWorks': 'Cómo Funciona',
    'nav.useCases': 'Casos de Uso',
    'nav.faqs': 'Preguntas Frecuentes',
    'footer.terms': 'Términos y Privacidad',
    'common.connectWallet': 'Conectar Billetera',
    'common.disconnect': 'Desconectar',
    'common.loading': 'Cargando...',
    'common.submit': 'Enviar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.toggleLanguage': 'Cambiar idioma',
    'common.processing': 'Procesando...',
    'common.months': 'meses',
    'common.members': 'miembros',
    'common.total': 'Total',
    'common.active': 'Activo',
    'common.current': 'Actual',
    'landing.title': 'TrustFlow',
    'landing.subtitle': 'Red de Confianza Resistente a Sybil',
    'communities.title': 'Comunidades',
    'communities.description': 'Descubre y únete a redes de confianza con criterios de respaldo personalizados',
    'communities.create': 'Crear Comunidad',
    'communities.viewDashboard': 'Ver Panel de Préstamos',
    'communities.myCommunities': 'Mis Comunidades',
    'communities.allCommunities': 'Todas las Comunidades',
    'communities.viewDetails': 'Ver Detalles',
    'communities.dashboard': 'Panel',
    'communities.noCommunities': 'Aún no hay comunidades',
    'communities.beFirst': 'Sé el primero en crear una red de confianza',
    'communities.prompt': 'Pregunta',
    'communities.community': 'Comunidad',
    'communities.public': 'Pública',
    'communities.private': 'Privada',
    'communities.notFound': 'Comunidad no encontrada',
    'overview.title': 'Resumen',
    'overview.description': 'Tu centro de confianza personal: ve tu puntuación, da respaldos y administra tu red',
    'credit.title': 'Crédito',
    'credit.description': 'Accedé a microcréditos según tu puntaje de confianza',
    'credit.connectWallet': 'Conectar Billetera',
    'credit.connectWalletDesc': 'Por favor conectá tu billetera para acceder al crédito',
    'credit.loadingInfo': 'Cargando información de crédito...',
    'credit.trustProfile': 'Perfil de Confianza',
    'credit.trustProfileDesc': 'Tus métricas de confianza (solo informativas)',
    'credit.sybilResistance': 'Resistencia Sybil',
    'credit.healthIndex': 'Índice de Salud',
    'credit.endorsedMember': 'Miembro avalado de la red de confianza',
    'credit.metricsAdvisory': 'Estas métricas son solo informativas. Todos los miembros pueden solicitar préstamos durante la fase piloto.',
    'credit.noMetrics': 'No hay métricas de confianza disponibles aún',
    'credit.noMetricsInfo': 'Aún podés solicitar préstamos durante la fase piloto. Conseguí avales de miembros confiables para construir tu perfil.',
    'credit.applyLoan': 'Solicitar Préstamo',
    'credit.applyLoanDesc': 'Seleccioná el monto y período de pago',
    'credit.fullName': 'Nombre Completo',
    'credit.fullNamePlaceholder': 'Ej: María González',
    'credit.loanAmount': 'Monto del Préstamo (ARS)',
    'credit.paymentTerm': 'Período de Pago',
    'credit.applyLoanButton': 'Solicitar Préstamo',
    'credit.tabApply': 'Solicitar Préstamo',
    'credit.tabActive': 'Préstamo Activo',
    'credit.tabHistory': 'Historial',
    'credit.activeLoan': 'Préstamo Activo',
    'credit.paymentProgress': 'Progreso de Pago',
    'credit.nextPayment': 'Próximo Pago',
    'credit.dueOn': 'vence el',
    'credit.makePayment': 'Realizar Pago',
    'credit.makePaymentDesc': 'Pagá tu próxima cuota',
    'credit.paymentAmountARS': 'Monto del Pago (ARS)',
    'credit.makePaymentButton': 'Realizar Pago',
    'credit.loanHistory': 'Historial de Préstamos',
    'credit.loanHistoryDesc': 'Tus préstamos pasados y actuales',
    'credit.noLoans': 'Aún no tenés préstamos',
    'credit.statusPaid': 'PAGADO',
    'credit.statusActive': 'ACTIVO',
    'credit.statusDefault': 'IMPAGO',
    'credit.loanCreatedSuccess': 'Préstamo creado exitosamente',
    'credit.loanDisbursed': 'Tu préstamo ha sido desembolsado',
    'credit.errorCreatingLoan': 'Error al crear el préstamo',
    'credit.paymentSuccess': 'Pago exitoso',
    'credit.paymentProcessed': 'Tu pago ha sido procesado',
    'credit.errorPayment': 'Error en el pago',
    'credit.errorNameRequired': 'Por favor ingresá tu nombre completo',
    'communityDetail.accepted': 'Avalados',
    'communityDetail.health': 'Salud',
    'communityDetail.minCut': 'Min-Cut',
    'communityDetail.avgResistance': 'Resistencia Prom.',
    'communityDetail.activeLoans': 'Préstamos Activos',
    'communityDetail.onTime': 'A Tiempo',
    'communityDetail.rate90d': 'Tasa 90d',
    'communityDetail.vouches': 'Avales',
    'communityDetail.sponsors': 'Sponsors',
    'communityDetail.tabOverview': 'Resumen',
    'communityDetail.tabCredit': 'Crédito',
    'communityDetail.tabSupport': 'Apoyar',
    'communityDetail.tabTrust': 'Confianza',
    'communityDetail.tabImpact': 'Impacto',
    'communityDetail.tabUpdates': 'Novedades',
    'communityDetail.tabPeople': 'Personas',
    'communityDetail.tabTransparency': 'Transparencia',
    'communityDetail.trustDistribution': 'Distribución de Confianza',
    'communityDetail.trustDistributionDesc': 'Miembros por nivel de confianza',
    'communityDetail.networkMetrics': 'Métricas de Red',
    'communityDetail.networkMetricsDesc': 'Estadísticas de cálculo más recientes',
    'communityDetail.avgFlow': 'Flujo Promedio',
    'communityDetail.avgMinCut': 'Min-Cut Promedio',
    'communityDetail.activeParticipants': 'Participantes Activos',
    'communityDetail.graphHealth': 'Salud del Grafo',
    'communityDetail.aboutCommunity': 'Sobre Esta Comunidad',
    'communityDetail.endorsementCriteria': 'Criterios de Aval',
    'communityDetail.memberEndorse': 'Los miembros se avalan mutuamente afirmando:',
    'communityDetail.cryptoVerified': 'Todos los avales son verificados criptográficamente contra el hash de la pregunta para garantizar consistencia.',
    'communityDetail.connectForCredit': 'Conectar Tu Billetera',
    'communityDetail.connectForCreditDesc': 'Conectá tu billetera para verificar tu elegibilidad crediticia y ver ofertas de préstamos',
    'communityDetail.creditAccess': 'Acceso a Crédito',
    'communityDetail.creditAccessDesc': 'Solicitar microcréditos o administrar tu crédito activo',
    'communityDetail.eligibilityStatus': 'Tu Estado de Elegibilidad',
    'communityDetail.eligible': 'Elegible',
    'communityDetail.notEligible': 'Aún No Elegible',
    'communityDetail.eligibleDesc': 'Cumplís los requisitos de confianza y podés solicitar crédito en esta comunidad.',
    'communityDetail.notEligibleDesc': 'Construí confianza obteniendo avales de miembros de la comunidad para desbloquear el acceso a crédito.',
    'communityDetail.viewMyLoan': 'Ver Mi Préstamo',
    'communityDetail.applyForCredit': 'Solicitar Crédito',
    'communityDetail.viewOffers': 'Ver Ofertas',
    'communityDetail.yourActiveLoans': 'Tus Préstamos Activos',
    'communityDetail.loanNumber': 'Préstamo #',
    'communityDetail.principal': 'Principal',
    'communityDetail.term': 'Plazo',
    'communityDetail.apr': 'TNA',
    'communityDetail.nextDue': 'Próximo Vto.',
    'communityDetail.howToJoin': 'Cómo Unirse a Esta Comunidad',
    'communityDetail.toEarnTrust': 'Para ganar confianza en',
    'communityDetail.step1': 'Obtené avales de miembros confiables existentes que puedan afirmar:',
    'communityDetail.step2': 'Construí rutas redundantes a través de la red (min-cut ≥',
    'communityDetail.step3': 'Asegurate de tener conexiones independientes (≥',
    'communityDetail.step3cont': 'rutas independientes)',
    'communityDetail.step4': 'Mantené conexiones de calidad con al menos',
    'communityDetail.step4cont': 'miembros semilla',
    'communityDetail.step5': 'Cada semilla debe proporcionar ≥',
    'communityDetail.step5cont': 'de tu flujo',
    'communityDetail.connectForSupport': 'Conectá tu billetera para ver y apoyar préstamos en esta comunidad',
    'communityDetail.interestBuydown': 'Reducción de Interés',
    'communityDetail.repayAssist': 'Asistencia de Pago',
    'communityDetail.myPortfolio': 'Mi Cartera',
    'communityDetail.ibdDesc': 'Comprometete mensualmente con USDC para reducir la tasa de interés del prestatario',
    'communityDetail.noLoansIBD': 'No hay préstamos activos disponibles para Reducción de Interés en esta comunidad.',
    'communityDetail.setMonthlyCommitment': 'Establecer Compromiso Mensual',
    'communityDetail.monthlyCommitmentDesc': 'Elegí cuánto contribuir cada mes para reducir la tasa de interés del prestatario',
    'communityDetail.monthlyAmount': 'Monto Mensual',
    'communityDetail.commitRange': 'Comprometete entre $100k - $2M ARS por mes',
    'communityDetail.activateCommitment': 'Activar Compromiso Mensual',
    'communityDetail.creating': 'Creando...',
    'communityDetail.ibdCreated': 'Reducción de Interés Creada',
    'communityDetail.ibdCreatedDesc': 'Tu compromiso mensual ha sido activado para reducir la tasa de interés del prestatario.',
    'communityDetail.errorCreatingCommitment': 'Error al Crear Compromiso',
    'communityDetail.raActivated': 'Asistencia de Pago Activada',
    'communityDetail.raActivatedDesc': 'Cubriste la cuota atrasada. El prestatario te reembolsará con un 6% de prima.',
    'communityDetail.errorCoveringInstallment': 'Error al Cubrir Cuota',
    'communityDetail.apiIntegration': 'Integración API',
    'communityDetail.apiIntegrationDesc': 'Conectar aplicaciones externas a esta comunidad',
    'communityDetail.apiKey': 'Clave API',
    'communityDetail.apiKeyCopied': 'Clave API Copiada',
    'communityDetail.apiKeyCopiedDesc': 'La clave API se ha copiado al portapapeles',
    'communityDetail.apiKeyWarning': 'Mantené esta clave segura. Permite que aplicaciones externas lean puntuaciones de confianza y envíen avales en nombre de los usuarios.',
    'communityDetail.endpoints': 'Endpoints Disponibles',
    'createCommunity.title': 'Crear una Comunidad',
    'createCommunity.description': 'Construí una red de confianza con criterios de aval personalizados',
    'createCommunity.step1': '1. Elegir una Plantilla',
    'createCommunity.templateDesc': 'Seleccioná una política preconfigurada o empezá desde cero',
    'createCommunity.step2': '2. Detalles de la Comunidad',
    'createCommunity.basicInfo': 'Información Básica',
    'createCommunity.communityName': 'Nombre de la Comunidad',
    'createCommunity.communityNamePlaceholder': 'Ej: Red de Freelancers Tecnológicos',
    'createCommunity.descriptionLabel': 'Descripción',
    'createCommunity.descriptionPlaceholder': 'Describí el propósito y objetivos de tu comunidad...',
    'createCommunity.endorsementPrompt': 'Pregunta de Aval',
    'createCommunity.promptPlaceholder': 'Confío en que esta persona...',
    'createCommunity.walletRequired': 'Billetera no conectada',
    'createCommunity.walletRequiredDesc': 'Por favor conectá tu billetera para crear una comunidad',
    'createCommunity.nameRequired': 'Nombre requerido',
    'createCommunity.nameRequiredDesc': 'Por favor ingresá un nombre de comunidad',
    'createCommunity.createButton': 'Crear Comunidad',
    'createCommunity.communityCreated': '¡Comunidad creada!',
    'createCommunity.creatorFirstSeed': 'ha sido creada. Sos automáticamente la primera semilla.',
    'createCommunity.errorCreating': 'Error al crear la comunidad',
    'createCommunity.errorCreatingDesc': 'Falló la creación de la comunidad',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
